import { memo, FC } from "react";
import styled from "styled-components";
import {
  Text,
  Button,
  Box,
  Flex,
  Table,
  Thead,
  Tbody,
  Tr,
  Th,
  Td,
  Accordion,
  AccordionItem,
  AccordionButton,
  AccordionIcon,
  AccordionPanel,
} from "@chakra-ui/react";

export const Private: FC = memo(() => {
  return (
    <>
      <Box background={"white.50"} m={10} p={20} rounded={20}>
        <Accordion allowMultiple>
          <AccordionItem outlineOffset={0}>
            <AccordionButton>
              <Box flex="1" textAlign="left" fontWeight="bold" fontSize={30}>
                基本情報
              </Box>
              <AccordionIcon />
            </AccordionButton>
            <AccordionPanel pb={4}>
              <Table variant="striped" colorScheme="gray">
                <Thead>
                  <Tr>
                    <Th>項目名</Th>
                    <Th>内容</Th>
                  </Tr>
                </Thead>
                <Tbody>
                  <Tr>
                    <Td>スタッフID</Td>
                    <Td>0000</Td>
                  </Tr>
                  <Tr>
                    <Td>年齢</Td>
                    <Td>00歳</Td>
                  </Tr>
                  <Tr>
                    <Td>性別</Td>
                    <Td>女</Td>
                  </Tr>
                  <Tr>
                    <Td>最寄駅</Td>
                    <Td>ほげほげ駅(ほげほげ線)</Td>
                  </Tr>
                  <Tr>
                    <Td>稼働開始日</Td>
                    <Td>応相談</Td>
                  </Tr>
                  <Tr>
                    <Td>エンジニア歴</Td>
                    <Td>
                      0年0ヵ月
                      <ul>
                        <li>SE経験:0年0ヵ月</li>
                        <li>PG/作業員経験:0年0ヵ月</li>
                      </ul>
                    </Td>
                  </Tr>
                  <Tr>
                    <Td>IT全体歴</Td>
                    <Td>0年0ヵ月</Td>
                  </Tr>
                </Tbody>
              </Table>
            </AccordionPanel>
          </AccordionItem>
        </Accordion>

        <_Title>スキル要約</_Title>

        <Table variant="striped" colorScheme="gray">
          <Thead>
            <Tr>
              <Th>項目名</Th>
              <Th>内容</Th>
            </Tr>
          </Thead>
          <Tbody>
            <Tr>
              <Td>動作環境(OS)</Td>
              <Td>
                <Flex>
                  <Box
                    backgroundColor="gray.400"
                    borderRadius={5}
                    ml={2}
                    px={2}
                    py={1}
                    textColor="white"
                  >
                    Windows
                  </Box>
                  <Box
                    backgroundColor="gray.400"
                    borderRadius={5}
                    ml={2}
                    px={2}
                    py={1}
                    textColor="white"
                  >
                    Mac
                  </Box>
                  <Box
                    backgroundColor="gray.400"
                    borderRadius={5}
                    ml={2}
                    px={2}
                    py={1}
                    textColor="white"
                  >
                    Linux
                  </Box>
                </Flex>
              </Td>
            </Tr>
            <Tr>
              <Td>フレームワーク</Td>
              <Td>
                <Flex>
                  <Box
                    backgroundColor="gray.400"
                    borderRadius={5}
                    ml={2}
                    px={2}
                    py={1}
                    textColor="white"
                  >
                    Windows
                  </Box>
                  <Box
                    backgroundColor="gray.400"
                    borderRadius={5}
                    ml={2}
                    px={2}
                    py={1}
                    textColor="white"
                  >
                    Mac
                  </Box>
                  <Box
                    backgroundColor="gray.400"
                    borderRadius={5}
                    ml={2}
                    px={2}
                    py={1}
                    textColor="white"
                  >
                    Linux
                  </Box>
                </Flex>
              </Td>
            </Tr>
            <Tr>
              <Td>言語</Td>
              <Td>
                <Flex>
                  <Box
                    backgroundColor="gray.400"
                    borderRadius={5}
                    ml={2}
                    px={2}
                    py={1}
                    textColor="white"
                  >
                    Windows
                  </Box>
                  <Box
                    backgroundColor="gray.400"
                    borderRadius={5}
                    ml={2}
                    px={2}
                    py={1}
                    textColor="white"
                  >
                    Mac
                  </Box>
                  <Box
                    backgroundColor="gray.400"
                    borderRadius={5}
                    ml={2}
                    px={2}
                    py={1}
                    textColor="white"
                  >
                    Linux
                  </Box>
                </Flex>
              </Td>
            </Tr>
            <Tr>
              <Td>ライブラリ</Td>
              <Td>
                <Flex>
                  <Box
                    backgroundColor="gray.400"
                    borderRadius={5}
                    ml={2}
                    px={2}
                    py={1}
                    textColor="white"
                  >
                    Windows
                  </Box>
                  <Box
                    backgroundColor="gray.400"
                    borderRadius={5}
                    ml={2}
                    px={2}
                    py={1}
                    textColor="white"
                  >
                    Mac
                  </Box>
                  <Box
                    backgroundColor="gray.400"
                    borderRadius={5}
                    ml={2}
                    px={2}
                    py={1}
                    textColor="white"
                  >
                    Linux
                  </Box>
                </Flex>
              </Td>
            </Tr>
            <Tr>
              <Td>ツール・その他</Td>
              <Td>
                <Flex>
                  <Box
                    backgroundColor="gray.400"
                    borderRadius={5}
                    ml={2}
                    px={2}
                    py={1}
                    textColor="white"
                  >
                    Windows
                  </Box>
                  <Box
                    backgroundColor="gray.400"
                    borderRadius={5}
                    ml={2}
                    px={2}
                    py={1}
                    textColor="white"
                  >
                    Mac
                  </Box>
                  <Box
                    backgroundColor="gray.400"
                    borderRadius={5}
                    ml={2}
                    px={2}
                    py={1}
                    textColor="white"
                  >
                    Linux
                  </Box>
                </Flex>
              </Td>
            </Tr>
            <Tr>
              <Td>担当開発工程</Td>
              <Td>
                <Flex>
                  <Box
                    backgroundColor="gray.400"
                    borderRadius={5}
                    ml={2}
                    px={2}
                    py={1}
                    textColor="white"
                  >
                    Windows
                  </Box>
                  <Box
                    backgroundColor="gray.400"
                    borderRadius={5}
                    ml={2}
                    px={2}
                    py={1}
                    textColor="white"
                  >
                    Mac
                  </Box>
                  <Box
                    backgroundColor="gray.400"
                    borderRadius={5}
                    ml={2}
                    px={2}
                    py={1}
                    textColor="white"
                  >
                    Linux
                  </Box>
                </Flex>
              </Td>
            </Tr>
          </Tbody>
        </Table>

        <_Title>自己PR・前職経験</_Title>
        <Box ml={10} width={900}>
          後で改行調整しなきゃ
          あああああああああああああああああああああああああああああああああああああああああああああああ
          あああああああああああああああああ
          ああああああああああああああああああああああああああああああああ
          ああああああああああああああああああああああああああああああああああああああああああ
          ああああああああああああああああああああああああああああああああ
          ああああああああああああああああああああああああああああああああああああああああああ
          あああああああああああああああああああああああああああああああああ
          あああああああああああああああああああああああああああああああああ
        </Box>

        <_Title>業務外に取り組んでいること</_Title>
        <div>
          <div>項目名を入れたいな</div>
          <div>ほげほげほげほげほげほげほげほげほげほげほげほげほげほげ</div>
        </div>
        <div>
          <div>本を読んでいる</div>
          <div>ほげほげほげほげほげほげほげほげほげほげほげほげほげほげ</div>
        </div>
        <_Title>資格</_Title>
        <ul>
          <li>ITパスポート(0000/00)</li>
          <li>基本情報技術者試験(0000/00)</li>
          <li>色彩検定1級(0000/00)</li>
        </ul>
        <_Title>前職</_Title>
        <div>
          <div>業界</div>
          <div>ほげほげほげほげほげほげほげほげほげほげほげほげほげほげ</div>
        </div>

        <_Title>開発経験</_Title>

        <Table variant="striped" colorScheme="gray">
          <Thead>
            <Tr>
              <Th>項目名</Th>
              <Th>内容</Th>
            </Tr>
          </Thead>
          <Tbody>
            <Tr>
              <Td>プロジェクト名</Td>
              <Td>ほげほげサイト</Td>
            </Tr>
            <Tr>
              <Td>期間</Td>
              <Td>0000ヵ月</Td>
            </Tr>
            <Tr>
              <Td>担当役割</Td>
              <Td>
                <Flex>
                  <Box
                    backgroundColor="gray.400"
                    borderRadius={5}
                    ml={2}
                    px={2}
                    py={1}
                    textColor="white"
                  >
                    Windows
                  </Box>
                  <Box
                    backgroundColor="gray.400"
                    borderRadius={5}
                    ml={2}
                    px={2}
                    py={1}
                    textColor="white"
                  >
                    Mac
                  </Box>
                  <Box
                    backgroundColor="gray.400"
                    borderRadius={5}
                    ml={2}
                    px={2}
                    py={1}
                    textColor="white"
                  >
                    Linux
                  </Box>
                </Flex>
              </Td>
            </Tr>
            <Tr>
              <Td>チーム人数</Td>
              <Td>00</Td>
            </Tr>
            <Tr>
              <Td>動作環境(OS)</Td>
              <Td>
                <Flex>
                  <Box
                    backgroundColor="gray.400"
                    borderRadius={5}
                    ml={2}
                    px={2}
                    py={1}
                    textColor="white"
                  >
                    Windows
                  </Box>
                  <Box
                    backgroundColor="gray.400"
                    borderRadius={5}
                    ml={2}
                    px={2}
                    py={1}
                    textColor="white"
                  >
                    Mac
                  </Box>
                  <Box
                    backgroundColor="gray.400"
                    borderRadius={5}
                    ml={2}
                    px={2}
                    py={1}
                    textColor="white"
                  >
                    Linux
                  </Box>
                </Flex>
              </Td>
            </Tr>
            <Tr>
              <Td>言語</Td>
              <Td>
                <Flex>
                  <Box
                    backgroundColor="gray.400"
                    borderRadius={5}
                    ml={2}
                    px={2}
                    py={1}
                    textColor="white"
                  >
                    Windows
                  </Box>
                  <Box
                    backgroundColor="gray.400"
                    borderRadius={5}
                    ml={2}
                    px={2}
                    py={1}
                    textColor="white"
                  >
                    Mac
                  </Box>
                  <Box
                    backgroundColor="gray.400"
                    borderRadius={5}
                    ml={2}
                    px={2}
                    py={1}
                    textColor="white"
                  >
                    Linux
                  </Box>
                </Flex>
              </Td>
            </Tr>
            <Tr>
              <Td>フレームワーク</Td>
              <Td>Vue.js</Td>
            </Tr>
            <Tr>
              <Td>ライブラリ</Td>
              <Td>
                <Flex>
                  <Box
                    backgroundColor="gray.400"
                    borderRadius={5}
                    ml={2}
                    px={2}
                    py={1}
                    textColor="white"
                  >
                    Windows
                  </Box>
                  <Box
                    backgroundColor="gray.400"
                    borderRadius={5}
                    ml={2}
                    px={2}
                    py={1}
                    textColor="white"
                  >
                    Mac
                  </Box>
                  <Box
                    backgroundColor="gray.400"
                    borderRadius={5}
                    ml={2}
                    px={2}
                    py={1}
                    textColor="white"
                  >
                    Linux
                  </Box>
                </Flex>
              </Td>
            </Tr>
            <Tr>
              <Td>ツール・その他</Td>
              <Td>
                <Flex>
                  <Box
                    backgroundColor="gray.400"
                    borderRadius={5}
                    ml={2}
                    px={2}
                    py={1}
                    textColor="white"
                  >
                    Windows
                  </Box>
                  <Box
                    backgroundColor="gray.400"
                    borderRadius={5}
                    ml={2}
                    px={2}
                    py={1}
                    textColor="white"
                  >
                    Mac
                  </Box>
                  <Box
                    backgroundColor="gray.400"
                    borderRadius={5}
                    ml={2}
                    px={2}
                    py={1}
                    textColor="white"
                  >
                    Linux
                  </Box>
                </Flex>
              </Td>
            </Tr>
          </Tbody>
        </Table>
        <div>プロジェクト詳細</div>
        <Box ml={10} width={900}>
          後で改行調整しなきゃ
          あああああああああああああああああああああああああああああああああああああああああああああああ
          あああああああああああああああああ
          ああああああああああああああああああああああああああああああああ
          ああああああああああああああああああああああああああああああああああああああああああ
          ああああああああああああああああああああああああああああああああ
          ああああああああああああああああああああああああああああああああああああああああああ
          あああああああああああああああああああああああああああああああああ
          あああああああああああああああああああああああああああああああああ
        </Box>
      </Box>
    </>
  );
});

const _Title = styled.div`
  font-weight: bold;
  font-size: 30px;
  margin: 60px 0px 10px 0px;
`;
